app = 'web-check-api'
primary_region = 'lhr'

[build]

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  interval = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  port = 8080
  timeout = "2s"
  tls_skip_verify = false
